// @vitest-environment jsdom
/**
 * Tests for compressPdfKeepText — the keep-text (structural + JPEG re-encode)
 * pipeline that MUST NEVER rasterize. Text operators must survive every pass.
 *
 * We generate a small text-heavy PDF with pdf-lib rather than depending on a
 * large fixture. This keeps tests fast and avoids fixture drift.
 */
import { describe, it, expect, beforeAll } from 'vitest'
import { PDFDocument, StandardFonts } from 'pdf-lib'
import * as pako from 'pako'
import * as fs from 'node:fs'
import * as path from 'node:path'
import { compressPdfKeepText } from '../pdf'

async function makeTextHeavyPdf(name = 'text.pdf'): Promise<File> {
  const doc = await PDFDocument.create()
  const font = await doc.embedFont(StandardFonts.Helvetica)
  // Add several pages of text so the PDF has meaningful size and real text
  // operators (Tj) in its content streams.
  for (let p = 0; p < 4; p++) {
    const page = doc.addPage([612, 792])
    for (let i = 0; i < 40; i++) {
      page.drawText(
        `Line ${i} on page ${p}: keep-text pipeline must preserve every character.`,
        { x: 50, y: 750 - i * 16, size: 10, font }
      )
    }
  }
  const bytes = await doc.save()
  return new File([bytes], name, { type: 'application/pdf' })
}

function decodeContentStreams(pdfBytes: Uint8Array): string {
  // Content streams in a compressed PDF are usually /FlateDecode'd. We locate
  // each `stream ... endstream` block and try to inflate it; if inflate fails
  // (uncompressed stream), we decode the raw bytes as latin1.
  const latin1 = new TextDecoder('latin1').decode(pdfBytes)
  const out: string[] = [latin1] // include the raw text — object-stream contents
  const streamRe = /stream\r?\n([\s\S]*?)\r?\nendstream/g
  let m: RegExpExecArray | null
  while ((m = streamRe.exec(latin1)) !== null) {
    const start = m.index + m[0].indexOf('\n') + 1
    const end = start + m[1].length
    const raw = pdfBytes.subarray(start, end)
    try {
      const inflated = pako.inflate(raw)
      out.push(new TextDecoder('latin1').decode(inflated))
    } catch {
      // Not deflated — already accounted for in the raw latin1 dump.
    }
  }
  return out.join('\n')
}

let bigTarget: File

beforeAll(async () => {
  bigTarget = await makeTextHeavyPdf()
})

describe('compressPdfKeepText', () => {
  it('returns ok=true when the target is easily achievable', async () => {
    const result = await compressPdfKeepText(bigTarget, 5_000_000)
    expect(result.ok).toBe(true)
    if (result.ok) {
      expect(result.bytes).toBeLessThanOrEqual(5_000_000)
      expect(result.passesRun.length).toBeGreaterThan(0)
      expect(result.passesRun[0]).toBe('structural-cleanup')
    }
  })

  it('returns ok=false with best bytes when the target is unreachable without rasterize', async () => {
    const result = await compressPdfKeepText(bigTarget, 100)
    expect(result.ok).toBe(false)
    if (!result.ok) {
      expect(result.reason).toBe('unachievable-keep-text')
      expect(result.bestBytes).toBeGreaterThan(100)
      expect(result.targetBytes).toBe(100)
      expect(result.passesRun).toContain('structural-cleanup')
      expect(result.passesRun).toContain('jpeg-recompress')
    }
  })

  it('never rasterizes — output PDF still contains text operators even on tiny targets', async () => {
    const result = await compressPdfKeepText(bigTarget, 100)
    const blob = result.ok ? result.blob : result.bestBlob
    const bytes = new Uint8Array(await blob.arrayBuffer())
    const decoded = decodeContentStreams(bytes)
    const hasTextOp = /\bTj\b|\bTJ\b|\bT\*\b|\bTL\b/.test(decoded)
    expect(hasTextOp).toBe(true)
  })

  it('downsamples Flate/PNG images, not just JPEG', async () => {
    // Fixture generated by spike/scripts/gen-flate-fixture.ts. Contains a page
    // of text plus a large FlateDecode / DeviceRGB / BPC 8 image XObject.
    const fixturePath = path.join(
      process.cwd(),
      'fixtures',
      'pdf-keep-text',
      'text-with-png.pdf'
    )
    const bytes = fs.readFileSync(fixturePath)
    const inputSize = bytes.byteLength
    const file = new File([new Uint8Array(bytes)], 'text-with-png.pdf', {
      type: 'application/pdf',
    })

    // Ask for a target well below the input size so the JPEG/Flate pass runs.
    const target = Math.floor(inputSize / 4)
    const result = await compressPdfKeepText(file, target)

    const blob = result.ok ? result.blob : result.bestBlob
    const outSize = blob.size
    // The PNG in the fixture is ~400KB. Downsampling + JPEG-recompress must
    // produce a materially smaller output — well under half the input. If
    // the Flate/PNG branch is missing, only structural cleanup runs and the
    // output stays within a few bytes of the input.
    expect(outSize).toBeLessThan(Math.floor(inputSize / 2))

    // Text operators must still be present — no rasterization is allowed.
    const outBytes = new Uint8Array(await blob.arrayBuffer())
    const decoded = decodeContentStreams(outBytes)
    const hasTextOp = /\bTj\b|\bTJ\b|\bT\*\b|\bTL\b/.test(decoded)
    expect(hasTextOp).toBe(true)
  })
})
