import { pdfToText } from '@/lib/converters/pdf'
import type { ToolConfig } from '@/lib/types'

export const config: ToolConfig = {
  slug: 'pdf-to-text',
  title: 'PDF to Text Converter',
  subtitle: 'Extract all text from any PDF. Built for batches.',
  category: 'pdf',
  accepts: ['application/pdf'],
  acceptsExt: ['.pdf'],
  outputExt: '.txt',
  convertFn: pdfToText,

  limitationNote: {
    summary: 'When does this work best?',
    body: 'This tool extracts embedded text from the PDF. If your PDF is a scanned document (an image of a page rather than a text document), the output will be empty or minimal. For scanned PDFs, use PDF to Word instead — it includes OCR.',
  },

  faq: [
    {
      q: 'What kinds of PDFs work with this tool?',
      a: 'PDFs that contain embedded text — such as documents exported from Word, reports generated by software, or digital-native PDFs. Scanned documents that are images of pages will produce empty or minimal output. For those, use the PDF to Word tool which includes OCR.',
    },
    {
      q: 'How is the text formatted in the output?',
      a: 'The tool extracts raw text content, preserving whitespace and line breaks from the PDF structure. Pages are separated by a "---" divider. Headings, tables, and columns may not render as expected — PDF text order is not always the same as reading order.',
    },
    {
      q: 'Can I extract text from password-protected PDFs?',
      a: 'Only if the PDF allows text copying. Password-protected PDFs that restrict copying will produce empty output. Remove the password restriction first using a PDF editor.',
    },
    {
      q: 'Does batch conversion work?',
      a: 'Yes. Drop multiple PDFs and each produces a separate .txt file. They all download as a ZIP.',
    },
    {
      q: 'Are my files uploaded to your servers?',
      a: 'Never. Text extraction runs entirely in your browser via WebAssembly. Your PDFs never leave your device.',
    },
  ],

  relatedTools: ['pdf-to-word', 'split-pdf', 'compress-pdf'],
  relatedArticles: [],

  meta: {
    title: 'PDF to Text Converter — ConvertYard',
    description: 'Extract text from PDF files in your browser. Batch convert 1,000 PDFs to .txt — no uploads, no account, entirely local.',
  },
}
